---
- hosts:
    - "{{ .provider_id }}"
  gather_facts: true
  roles:
    - precheck/env_check

- name: init cluster
  hosts:
    - localhost
  vars_files:
    - vars/main.yaml
  tasks:
      # https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap/index.html?highlight=ntp#additional-features
    - name: init cloud-config
      command: |
        cat {{ .cloud_config_dir }}/cloud-config
      register: cloud_config_out
    - name: set cloud-config to fact
      set_fact:
        cloud_config: "{{ cloud_config_out.stdout }}"
  roles:
    - init/init-artifacts
    - init/init-os

- name: install cluster
  hosts:
    - "{{ .provider_id }}"
  vars_files:
    - vars/main.yaml
  gather_facts: true
  roles:
    - install/cri
    - install/kubernetes
    - install/cloud-config
    - install/cni
    - install/storageclass