---
- name: Stop containerd
  include_tasks: uninstall_containerd.yaml
  when: .cri.container_manager == "containerd"

- name: Stop docker
  include_tasks: uninstall_docker.yaml
  when: .cri.container_manager == "docker"

# install cridockerd
- include_tasks: install_cridockerd.yaml
  when:
  - .cri.container_manager | eq  "docker"
  - .kube_version | semverCompare ">=v1.24.0"

- name: Delete residue files
  command: |
   rm -f /usr/local/bin/crictl