---
- name: Check if calicoctl is installed
  ignore_errors: true
  command: calicoctl --version
  register: calicoctl_install_version
- name: Install calicoctl
  when:
    - |
      or (.calicoctl_install_version.stderr | ne "") (.calicoctl_install_version.stdout | contains (printf "Client Version:    %s" .calico_version) | not)
  block:
    - name: Sync calicoctl to remote
      copy:
        src: |
          {{ .binary_dir }}/cni/caclico/calico/{{ .calico_version }}/{{ .binary_type.stdout }}/calicoctl
        dest: /usr/local/bin/calicoctl
        mode: 0755

- name: Sync calico package to remote
  copy:
    src: |
      {{ .binary_dir }}/cni/calico/tigera-operator--{{ .calico_version }}.tgz
    dest: |
      /etc/kubernetes/cni/tigera-operator-{{ .calico_version }}.tgz

- name: Generate calico custom value file
  copy:
    content: |
      {{ .cni.calico.values }}
    dest: |
      /etc/kubernetes/cni/calico-values.yaml

- name: Apply calico
  command: |
    helm install --create-namespace --namespace tigera-operator calico /etc/kubernetes/cni/tigera-operator-{{ .calico_version }}.tgz -f /etc/kubernetes/cni/calico-values.yaml
