---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kk
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels" .  | nindent 4}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kk
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kk
subjects:
  - kind: ServiceAccount
    name: kk
    namespace: {{ .Release.Namespace }}

