name: goreleaser

on:
  push:
    tags:
      - 'v4*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.repository == 'kubesphere/kubekey'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare
        id: prepare
        run: |
          LDFLAGS=$(bash hack/version.sh)
          
          echo "ldflags=${LDFLAGS}" >> "$GITHUB_OUTPUT"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LDFLAGS: ${{ steps.prepare.outputs.ldflags }}

      - name: Upload Extra File
        run: |
          TAG=${{ env.GITHUB_REF_NAME }} make generate
          gh release upload "$TAG" config/capkk/infrastructure-components.yaml --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}